
services:
  backend-service:
    build: .
    ports:
      - "5000:5000" # merged_app.py runs on port 5000 inside container, exposed on 5000
    env_file:
      - ../.env # Reference the .env file in the root directory
    environment:
      - QDRANT_URL=http://vector-db:6333 # Connect to Qdrant service
      - MONGO_URI=mongodb://mongodb:27017/genium # Internal Docker network connection for MongoDB
    depends_on:
      - vector-db
      - mongodb # Add dependency on MongoDB
    volumes:
      - .:/app
    networks:
      - genium-network
    command: python app.py # Changed to app.py

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - genium-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - genium-network

volumes:
 qdrant_data:
 mongodb_data:

networks:
 genium-network:
   driver: bridge