
# services:
#   streamlit-app:
#     build: .
#     ports:
#       - "8501:8501"

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - vector-db
    volumes:
      - .:/app
    networks:
      - genium-network

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - genium-network

volumes:
  qdrant_data:

networks:
  genium-network:
    driver: bridge