
services:
  backend-service:
    build: .
    ports:
      - "5000:5000" # merged_app.py runs on port 5000 inside container, exposed on 5000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Used for Gemini
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} # Used for Google Search
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
      - QDRANT_URL=http://vector-db:6333 # Connect to Qdrant service
    depends_on:
      - vector-db
    volumes:
      - .:/app
    networks:
      - genium-network
    command: python main_app.py

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - genium-network

volumes:
  qdrant_data:

networks:
  genium-network:
    driver: bridge